version: '3.7'

services:
  database_divino_design:
    image: postgres
    container_name: dbdivino
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=102030
      - POSTGRES_DB=dbdivino
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: divino_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
